In [1]:
import pandas as pd

In [2]:
import datetime as dt

In [3]:
start=dt.datetime(2024,4, 2 )

In [4]:
end=dt.datetime(2024, 6, 2)

In [8]:
symbols=['AAPL', 'MSFT', 'IBM', 'CRM', 'INTC' #, 'CSCO', 'NFLX', 'NVDA', 'PYPL', 'MU', 'UBER', 'MA', 'ADBE',
        # 'AKAM', 'ANET', 'ACN', 'APH', 'CDW', 'CDNS', 'IT', 'TSLA', 'CTSH', 'DXC', 'GLW', 'ADSK', 'FTV',
        #'FTNT', 'AMAT', 'UNH', 'JNJ ','MRK ','AMGN ','PFE ','ALGN ','ABBV' ,'A ','AOS','BDX','GILD','LLY','DHR','BIO','XRAY','BAX','BSX','BMY','EHC',
#'CNC','CVS','DVA','CAH','COO ','EW', 'GS',
#'JPM ',
#'AXP ',
#'TRV ',
#'AFL ',
#'AIG ',
#'ALL ',
#'AMP',
#'COF',
#'CFG',
#'CB',
#'BEN',
#'AON',
#'AIZ',
#'SCHW',
#'V ',
#'BR',
#'BIIB',
#'CMA',
#'CINF',
#'DFS',
#'BAC',
#'CME', 'BA',
#'MMM ',
#'CAT ',
#'HON ',
#'APD ',
#'ALLE ',
#'AME ',
#'ADI ',
#'ALB ',
#'CHRW',
#'DAL',
#'FDX',
#'CTAS',
#'GD',
#'FLS',
#'EMR',
#'CPRT',
#'DE',
#'FAST',
#'CMI',
#'CSX ',
#'EFX',
#'EXPD',
#'DOV ',
#'GE', 'HD',
#'MCD ',
#'NKE',
#'PG ',
#'WMT ',
#'KO ',
#'MO ',
#'AES ',
#'AAP ',
#'AMT ',
#'ARE',
#'BKNG',
#'DLTR',
#'CZR',
#'ARMK',
#'GRMN',
#'APTV',
#'CMG',
#'GM',
#'CL',
#'DG',
#'DRI',
#'KMX',
#'HRB',
#'FL',
#CAG',
#'CHD',
#'AZO',
#'GPS',
#'WBA',
#'DPZ',
#'ANSS',
#'CPB',
#'GPC',
#'BBY',
#'EL',
#'CCL',
#'GIS',
#'EXPE',
#'EBAY',
#'COTY',
#'BWA ',
#'STZ', 'CVX',
 #                       'DOW ',
 #                       'APA',
 #                      'FANG',
 #                      'EOG',
 #                       'EQT',
  #                      'DVN ',
   #                     'XOM',
    #                    'COP', 'AEE',
#'AEP ',
#'AWK ',
#'LNT',
#'FE',
#'EVRG',
#'EIX',
#'ATO',
#'ES',
#'DTE',
#'CMS',
#'DUK',
#'CNP', 'ALK' ,
#'AAL ', 'DHI',
 #                  'BXP',
  #                 'EXR',
   #                'AVB',
    #                'EQR',
     #               'CCI',
      #              'AIV',
       #             'ESS',
        #            'CBRE',
         #           'FRT',
          #          'DLR', 'DIS',
           #                  'CMCSA',
            #                   'VZ',
         #'FCX',
          #        'ECL',
           #       'DD ',
            #      'EMN',
             #     'CF',
              #    'FMC'
]

In [9]:
symbols=[symbol.strip() for symbol in symbols]

In [ ]:
pip install yfinance

In [11]:
import yfinance as yf

In [ ]:
pip install tqdm

In [13]:
from tqdm import tqdm

In [14]:
df=[]

In [15]:
for i, symbol in zip(tqdm(range(len(symbols)), desc="Downloading data..."), symbols):
    data = yf.download(symbol, start, end, progress=False)
    df.append(data['Close'])

Downloading data...: 100%|██████████| 5/5 [00:01<00:00,  3.29it/s]

In [16]:
df=pd.DataFrame(df).T

In [17]:
df.columns=symbols

In [18]:
df

                  AAPL        MSFT         IBM         CRM       INTC
Date
2024-04-02  168.839996  421.440002  188.880005  304.000000  43.939999
2024-04-03  169.649994  420.450012  190.899994  304.739990  40.330002
2024-04-04  168.820007  417.880005  187.940002  294.140015  39.730000
2024-04-05  169.580002  425.519989  189.139999  301.910004  38.709999
2024-04-08  168.449997  424.589996  189.820007  301.730011  37.980000
2024-04-09  169.669998  426.279999  189.309998  302.369995  38.330002
2024-04-10  167.779999  423.260010  186.039993  299.619995  37.200001
2024-04-11  175.039993  427.929993  185.899994  299.149994  37.630001
2024-04-12  176.550003  421.899994  182.270004  294.320007  35.689999
2024-04-15  172.690002  413.640015  181.250000  272.899994  36.310001
2024-04-16  169.380005  414.579987  183.750000  277.410004  36.259998
2024-04-17  168.000000  411.839996  183.100006  276.320007  35.680000
2024-04-18  167.039993  404.269989  181.470001  271.920013  35.040001
2024-04-19  165.000000  399.119995  181.580002  270.369995  34.200001
2024-04-22  165.839996  400.959991  181.899994  273.809998  34.410000
2024-04-23  166.899994  407.570007  182.190002  276.679993  34.279999
2024-04-24  169.020004  409.059998  184.100006  276.190002  34.500000
2024-04-25  169.889999  399.040009  168.910004  273.140015  35.110001
2024-04-26  169.300003  406.320007  167.130005  274.290009  31.879999
2024-04-29  173.500000  402.250000  167.429993  275.739990  31.360001
2024-04-30  170.330002  389.329987  166.199997  268.940002  30.469999
2024-05-01  169.300003  394.940002  164.429993  268.690002  30.370001
2024-05-02  173.029999  397.839996  164.690002  272.130005  30.510000
2024-05-03  183.380005  406.660004  165.710007  273.660004  30.900000
2024-05-06  181.710007  413.540009  168.610001  275.630005  30.969999
2024-05-07  182.399994  409.339996  168.380005  277.179993  30.680000
2024-05-08  182.740005  410.540009  169.899994  278.970001  30.000000
2024-05-09  184.570007  412.320007  166.270004  275.170013  30.090000
2024-05-10  183.050003  414.739990  167.149994  276.670013  29.850000
2024-05-13  186.279999  413.720001  167.559998  277.519989  30.510000
2024-05-14  187.429993  416.559998  167.360001  276.799988  31.049999
2024-05-15  189.720001  423.079987  168.259995  287.540009  31.270000
2024-05-16  189.839996  420.989990  168.970001  284.679993  32.029999
2024-05-17  189.869995  420.209991  169.029999  285.609985  31.830000
2024-05-20  191.039993  425.339996  169.919998  287.070007  32.099998
2024-05-21  192.350006  429.040009  173.470001  283.760010  31.740000
2024-05-22  190.899994  430.519989  173.690002  283.820007  31.420000
2024-05-23  186.880005  427.000000  170.669998  278.570007  30.080000
2024-05-24  189.979996  430.160004  170.889999  272.290009  30.719999
2024-05-28  189.990005  430.320007  169.660004  269.829987  31.059999
2024-05-29  190.289993  429.170013  167.050003  271.619995  30.129999
2024-05-30  191.289993  414.670013  165.630005  218.009995  30.190001
2024-05-31  192.250000  415.130005  166.850006  234.440002  30.850000

In [19]:
if df.duplicated().any() or df.isna().any().any():
  print("There are duplicates or nan prices. \n")
  df=df.dropna()
else:
  print("Everything is ok!!\n")

Everything is ok!!

In [20]:
df=df.reset_index()

In [21]:
df.columns.str.strip()

Index(['Date', 'AAPL', 'MSFT', 'IBM', 'CRM', 'INTC'], dtype='object')

In [22]:
df

         Date        AAPL        MSFT         IBM         CRM       INTC
0  2024-04-02  168.839996  421.440002  188.880005  304.000000  43.939999
1  2024-04-03  169.649994  420.450012  190.899994  304.739990  40.330002
2  2024-04-04  168.820007  417.880005  187.940002  294.140015  39.730000
3  2024-04-05  169.580002  425.519989  189.139999  301.910004  38.709999
4  2024-04-08  168.449997  424.589996  189.820007  301.730011  37.980000
5  2024-04-09  169.669998  426.279999  189.309998  302.369995  38.330002
6  2024-04-10  167.779999  423.260010  186.039993  299.619995  37.200001
7  2024-04-11  175.039993  427.929993  185.899994  299.149994  37.630001
8  2024-04-12  176.550003  421.899994  182.270004  294.320007  35.689999
9  2024-04-15  172.690002  413.640015  181.250000  272.899994  36.310001
10 2024-04-16  169.380005  414.579987  183.750000  277.410004  36.259998
11 2024-04-17  168.000000  411.839996  183.100006  276.320007  35.680000
12 2024-04-18  167.039993  404.269989  181.470001  271.920013  35.040001
13 2024-04-19  165.000000  399.119995  181.580002  270.369995  34.200001
14 2024-04-22  165.839996  400.959991  181.899994  273.809998  34.410000
15 2024-04-23  166.899994  407.570007  182.190002  276.679993  34.279999
16 2024-04-24  169.020004  409.059998  184.100006  276.190002  34.500000
17 2024-04-25  169.889999  399.040009  168.910004  273.140015  35.110001
18 2024-04-26  169.300003  406.320007  167.130005  274.290009  31.879999
19 2024-04-29  173.500000  402.250000  167.429993  275.739990  31.360001
20 2024-04-30  170.330002  389.329987  166.199997  268.940002  30.469999
21 2024-05-01  169.300003  394.940002  164.429993  268.690002  30.370001
22 2024-05-02  173.029999  397.839996  164.690002  272.130005  30.510000
23 2024-05-03  183.380005  406.660004  165.710007  273.660004  30.900000
24 2024-05-06  181.710007  413.540009  168.610001  275.630005  30.969999
25 2024-05-07  182.399994  409.339996  168.380005  277.179993  30.680000
26 2024-05-08  182.740005  410.540009  169.899994  278.970001  30.000000
27 2024-05-09  184.570007  412.320007  166.270004  275.170013  30.090000
28 2024-05-10  183.050003  414.739990  167.149994  276.670013  29.850000
29 2024-05-13  186.279999  413.720001  167.559998  277.519989  30.510000
30 2024-05-14  187.429993  416.559998  167.360001  276.799988  31.049999
31 2024-05-15  189.720001  423.079987  168.259995  287.540009  31.270000
32 2024-05-16  189.839996  420.989990  168.970001  284.679993  32.029999
33 2024-05-17  189.869995  420.209991  169.029999  285.609985  31.830000
34 2024-05-20  191.039993  425.339996  169.919998  287.070007  32.099998
35 2024-05-21  192.350006  429.040009  173.470001  283.760010  31.740000
36 2024-05-22  190.899994  430.519989  173.690002  283.820007  31.420000
37 2024-05-23  186.880005  427.000000  170.669998  278.570007  30.080000
38 2024-05-24  189.979996  430.160004  170.889999  272.290009  30.719999
39 2024-05-28  189.990005  430.320007  169.660004  269.829987  31.059999
40 2024-05-29  190.289993  429.170013  167.050003  271.619995  30.129999
41 2024-05-30  191.289993  414.670013  165.630005  218.009995  30.190001
42 2024-05-31  192.250000  415.130005  166.850006  234.440002  30.850000

In [ ]:
pip install pystan

In [ ]:
pip install prophet

In [25]:
from prophet import Prophet

In [26]:
from prophet.plot import plot_plotly

In [27]:
market_prices=[]

In [28]:
for i, symbol in zip(tqdm(range(len(symbols)), desc="Downloading data..."), symbols):
    next_data = yf.download(symbol, start=dt.datetime(2024, 6, 2), end=dt.datetime(2024, 7, 2), progress=False)
    market_prices.append(next_data['Close'])

Downloading data...: 100%|██████████| 5/5 [00:00<00:00,  8.23it/s]

In [29]:
market_prices=pd.DataFrame(market_prices).T

In [30]:
market_prices.columns=symbols

In [31]:
market_prices

                  AAPL        MSFT         IBM         CRM       INTC
Date
2024-06-03  194.029999  413.519989  165.279999  236.619995  30.290001
2024-06-04  194.350006  416.070007  165.809998  234.860001  30.030001
2024-06-05  195.869995  424.010010  167.380005  236.529999  30.780001
2024-06-06  194.479996  424.519989  168.199997  242.759995  30.420000
2024-06-07  196.889999  423.850006  170.009995  241.850006  30.740000
2024-06-10  193.119995  427.869995  170.380005  241.839996  30.910000
2024-06-11  207.149994  432.679993  169.320007  240.990005  30.920000
2024-06-12  213.070007  441.059998  169.000000  235.800003  30.760000
2024-06-13  214.240005  441.579987  169.119995  229.029999  30.459999
2024-06-14  212.490005  442.570007  169.210007  231.940002  30.450001
2024-06-17  216.669998  448.369995  169.500000  230.479996  30.980000
2024-06-18  214.289993  446.339996  170.550003  231.809998  30.629999
2024-06-20  209.679993  445.700012  173.919998  241.800003  30.620001
2024-06-21  207.490005  449.779999  172.460007  245.059998  31.090000
2024-06-24  208.139999  447.670013  175.009995  239.940002  30.570000
2024-06-25  209.070007  450.950012  172.600006  241.759995  30.740000
2024-06-26  213.250000  452.160004  171.869995  243.149994  30.540001
2024-06-27  214.100006  452.850006  170.850006  252.850006  30.590000
2024-06-28  210.619995  446.950012  172.949997  257.100006  30.969999
2024-07-01  216.750000  456.730011  175.100006  256.209991  30.840000

In [32]:
market_prices=market_prices.reset_index()

In [33]:
market_prices

         Date        AAPL        MSFT         IBM         CRM       INTC
0  2024-06-03  194.029999  413.519989  165.279999  236.619995  30.290001
1  2024-06-04  194.350006  416.070007  165.809998  234.860001  30.030001
2  2024-06-05  195.869995  424.010010  167.380005  236.529999  30.780001
3  2024-06-06  194.479996  424.519989  168.199997  242.759995  30.420000
4  2024-06-07  196.889999  423.850006  170.009995  241.850006  30.740000
5  2024-06-10  193.119995  427.869995  170.380005  241.839996  30.910000
6  2024-06-11  207.149994  432.679993  169.320007  240.990005  30.920000
7  2024-06-12  213.070007  441.059998  169.000000  235.800003  30.760000
8  2024-06-13  214.240005  441.579987  169.119995  229.029999  30.459999
9  2024-06-14  212.490005  442.570007  169.210007  231.940002  30.450001
10 2024-06-17  216.669998  448.369995  169.500000  230.479996  30.980000
11 2024-06-18  214.289993  446.339996  170.550003  231.809998  30.629999
12 2024-06-20  209.679993  445.700012  173.919998  241.800003  30.620001
13 2024-06-21  207.490005  449.779999  172.460007  245.059998  31.090000
14 2024-06-24  208.139999  447.670013  175.009995  239.940002  30.570000
15 2024-06-25  209.070007  450.950012  172.600006  241.759995  30.740000
16 2024-06-26  213.250000  452.160004  171.869995  243.149994  30.540001
17 2024-06-27  214.100006  452.850006  170.850006  252.850006  30.590000
18 2024-06-28  210.619995  446.950012  172.949997  257.100006  30.969999
19 2024-07-01  216.750000  456.730011  175.100006  256.209991  30.840000

In [34]:
market_prices.columns.str.strip()

Index(['Date', 'AAPL', 'MSFT', 'IBM', 'CRM', 'INTC'], dtype='object')

In [35]:
if market_prices.duplicated().any() or market_prices.isna().any().any():
  print("There are duplicates or nan prices.")
else:
  print("Everything is ok!!")

Everything is ok!!

In [36]:
pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (1.26.4)

In [37]:
import numpy as np

In [38]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.3.2)
Requirement already satisfied: numpy<2.0,>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)

In [39]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [40]:
def predict(symbol):
  df_f=df[['Date', symbol]].copy()
  df_f.columns=["ds", "y"]

  prophet=Prophet(daily_seasonality=True)
  prophet.fit(df_f)

  future_dates=prophet.make_future_dataframe(periods=30)
  predictions=prophet.predict(future_dates)
  predictions_filtered=predictions.iloc[-28:]

  closing_prices=market_prices[['Date', symbol]].copy()
  closing_prices.columns=["ds", "Closing_prices"]

  merged_df=pd.merge(predictions_filtered, closing_prices, on='ds', how='left')
  merged_df=merged_df.dropna()
  merged_df = merged_df[['ds', 'yhat', 'yhat_lower', 'yhat_upper', 'Closing_prices']]

  print(f'\nPredictions and market closing prices comparison  for the company {symbol}: \n')
  print(merged_df)

  y_true = merged_df['Closing_prices']
  y_pred = merged_df['yhat']

  mae = mean_absolute_error(y_true, y_pred)
  mse = mean_squared_error(y_true, y_pred)
  rmse = np.sqrt(mse)
  mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100

  print(f'\nModel Evaluation Metrics for {symbol}:')
  print(f'MAE: {mae:.2f}')
  print(f'RMSE: {rmse:.2f}')
  print(f'MAPE: {mape:.2f}%')

In [41]:
for symbol in symbols:
  predict(symbol)

INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/6vc6r5sq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/ffa1adtx.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.10/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=48183', 'data', 'file=/tmp/tmpxly7jtli/6vc6r5sq.json', 'init=/tmp/tmpxly7jtli/ffa1adtx.json', 'output', 'file=/tmp/tmpxly7jtli/prophet_modelgqo_3w_5/prophet_model-20240917210628.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
21:06:28 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
21:06:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/w8ehsqyg.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/duzqzrms.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.10/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=82774', 'data', 'file=/tmp/tmpxly7jtli/w8ehsqyg.json', 'init=/tmp/tmpxly7jtli/duzqzrms.json', 'output', 'file=/tmp/tmpxly7jtli/prophet_model8glppy6a/prophet_model-20240917210629.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
21:06:29 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Predictions and market closing prices comparison  for the company AAPL:

           ds        yhat  yhat_lower  yhat_upper  Closing_prices
0  2024-06-03  192.844011  189.759703  196.036269      194.029999
1  2024-06-04  192.207908  189.057434  195.322750      194.350006
2  2024-06-05  192.017742  188.788706  195.196756      195.869995
3  2024-06-06  192.814967  189.648986  195.976990      194.479996
4  2024-06-07  194.057629  190.698128  197.343376      196.889999
7  2024-06-10  194.146500  190.563903  197.658764      193.119995
8  2024-06-11  193.510397  190.087782  197.242175      207.149994
9  2024-06-12  193.320230  189.901389  197.076228      213.070007
10 2024-06-13  194.117455  190.457628  198.092846      214.240005
11 2024-06-14  195.360118  191.505468  199.542249      212.490005
14 2024-06-17  195.448988  191.257241  199.923404      216.669998
15 2024-06-18  194.812886  190.113771  199.319020      214.289993
17 2024-06-20  195.419944  190.471717  200.400130      209.679993
18 2024-06-21  196.662607  191.673442  201.992516      207.490005
21 2024-06-24  196.751477  190.848172  203.165636      208.139999
22 2024-06-25  196.115375  189.768491  202.883366      209.070007
23 2024-06-26  195.925208  189.299290  203.056596      213.250000
24 2024-06-27  196.722433  189.703226  203.802913      214.100006
25 2024-06-28  197.965096  190.649099  205.555460      210.619995

Model Evaluation Metrics for AAPL:
MAE: 11.62
RMSE: 13.61
MAPE: 5.51%

21:06:29 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/8wlj9vgu.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/1uscagc5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.10/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=52415', 'data', 'file=/tmp/tmpxly7jtli/8wlj9vgu.json', 'init=/tmp/tmpxly7jtli/1uscagc5.json', 'output', 'file=/tmp/tmpxly7jtli/prophet_modelxfcoma5v/prophet_model-20240917210630.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
21:06:30 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Predictions and market closing prices comparison  for the company MSFT:

           ds        yhat  yhat_lower  yhat_upper  Closing_prices
0  2024-06-03  427.177019  420.548827  433.860888      413.519989
1  2024-06-04  427.308431  421.204439  434.008181      416.070007
2  2024-06-05  428.350853  422.326402  434.867362      424.010010
3  2024-06-06  425.023609  418.325648  431.902005      424.519989
4  2024-06-07  427.112042  419.813889  433.938110      423.850006
7  2024-06-10  428.638092  421.419196  435.925555      427.869995
8  2024-06-11  428.769504  421.491403  436.088652      432.679993
9  2024-06-12  429.811927  422.286145  438.104148      441.059998
10 2024-06-13  426.484683  418.550538  434.915437      441.579987
11 2024-06-14  428.573116  420.405566  437.101212      442.570007
14 2024-06-17  430.099166  421.124367  439.260899      448.369995
15 2024-06-18  430.230578  420.379245  440.845453      446.339996
17 2024-06-20  427.945756  416.304530  439.266243      445.700012
18 2024-06-21  430.034189  418.927744  442.326795      449.779999
21 2024-06-24  431.560239  418.872905  445.812127      447.670013
22 2024-06-25  431.691651  417.799059  446.910990      450.950012
23 2024-06-26  432.734074  416.513158  448.235080      452.160004
24 2024-06-27  429.406830  413.842224  446.184678      452.850006
25 2024-06-28  431.495263  414.731267  449.287569      446.950012

Model Evaluation Metrics for MSFT:
MAE: 12.82
RMSE: 14.52
MAPE: 2.89%

21:06:30 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/nxnimcyz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/o8pbboni.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.10/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=21924', 'data', 'file=/tmp/tmpxly7jtli/nxnimcyz.json', 'init=/tmp/tmpxly7jtli/o8pbboni.json', 'output', 'file=/tmp/tmpxly7jtli/prophet_modeloi1nv0ql/prophet_model-20240917210631.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
21:06:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Predictions and market closing prices comparison  for the company IBM:

           ds        yhat  yhat_lower  yhat_upper  Closing_prices
0  2024-06-03  170.384321  166.993304  173.926092      165.279999
1  2024-06-04  170.890229  167.398350  174.477758      165.809998
2  2024-06-05  171.175687  167.933479  174.793866      167.380005
3  2024-06-06  168.651101  165.080662  172.291396      168.199997
4  2024-06-07  168.935584  165.455313  172.757698      170.009995
7  2024-06-10  170.901656  167.387932  174.441881      170.380005
8  2024-06-11  171.407564  167.413275  175.007176      169.320007
9  2024-06-12  171.693022  167.796053  175.277251      169.000000
10 2024-06-13  169.168436  165.332050  173.278080      169.119995
11 2024-06-14  169.452919  165.488676  173.402843      169.210007
14 2024-06-17  171.418991  167.052110  175.925383      169.500000
15 2024-06-18  171.924898  167.573655  176.198141      170.550003
17 2024-06-20  169.685771  164.747589  174.277362      173.919998
18 2024-06-21  169.970253  164.731303  174.691758      172.460007
21 2024-06-24  171.936326  166.630489  177.310090      175.009995
22 2024-06-25  172.442233  166.865051  178.021178      172.600006
23 2024-06-26  172.727692  167.036836  178.278291      171.869995
24 2024-06-27  170.203106  163.995841  176.411108      170.850006
25 2024-06-28  170.487588  164.020734  176.738352      172.949997

Model Evaluation Metrics for IBM:
MAE: 2.02
RMSE: 2.57
MAPE: 1.19%

21:06:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/9rjaonmv.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmpxly7jtli/8tk9qzch.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.10/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=36348', 'data', 'file=/tmp/tmpxly7jtli/9rjaonmv.json', 'init=/tmp/tmpxly7jtli/8tk9qzch.json', 'output', 'file=/tmp/tmpxly7jtli/prophet_model8jpd9_cy/prophet_model-20240917210631.csv', 'method=optimize', 'algorithm=newton', 'iter=10000']
21:06:31 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

Predictions and market closing prices comparison  for the company CRM:

           ds        yhat  yhat_lower  yhat_upper  Closing_prices
0  2024-06-03  263.191126  247.622597  278.919483      236.619995
1  2024-06-04  264.049404  249.251340  278.130512      234.860001
2  2024-06-05  265.323003  249.963950  279.324259      236.529999
3  2024-06-06  256.469243  241.138389  271.553989      242.759995
4  2024-06-07  258.421231  243.739735  272.759772      241.850006
7  2024-06-10  259.800991  244.088422  274.941561      241.839996
8  2024-06-11  260.659269  245.645542  275.840232      240.990005
9  2024-06-12  261.932869  246.853468  276.492247      235.800003
10 2024-06-13  253.079108  237.911168  268.157371      229.029999
11 2024-06-14  255.031096  240.672465  271.547928      231.940002
14 2024-06-17  256.410857  241.498998  271.589964      230.479996
15 2024-06-18  257.269135  242.357176  272.600687      231.809998
17 2024-06-20  249.688974  235.120687  265.226217      241.800003
18 2024-06-21  251.640962  237.423223  265.580153      245.059998
21 2024-06-24  253.020722  237.076380  267.444131      239.940002
22 2024-06-25  253.879000  238.968341  268.716214      241.759995
23 2024-06-26  255.152599  239.212037  270.805863      243.149994
24 2024-06-27  246.298839  230.557987  261.385109      252.850006
25 2024-06-28  248.250827  233.483027  263.616200      257.100006

Model Evaluation Metrics for CRM:
MAE: 18.12
RMSE: 19.69
MAPE: 7.64%

21:06:32 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

Predictions and market closing prices comparison  for the company INTC:

           ds       yhat  yhat_lower  yhat_upper  Closing_prices
0  2024-06-03  30.971201   29.865506   32.091991       30.290001
1  2024-06-04  31.406671   30.268685   32.512491       30.030001
2  2024-06-05  30.822140   29.823307   31.888048       30.780001
3  2024-06-06  30.950884   29.813949   31.982183       30.420000
4  2024-06-07  30.455411   29.393894   31.672758       30.740000
7  2024-06-10  30.998135   29.773997   32.148246       30.910000
8  2024-06-11  31.433605   30.353261   32.603111       30.920000
9  2024-06-12  30.849073   29.613757   32.014136       30.760000
10 2024-06-13  30.977818   29.795974   32.063199       30.459999
11 2024-06-14  30.482344   29.267228   31.723351       30.450001
14 2024-06-17  31.025068   29.775972   32.280613       30.980000
15 2024-06-18  31.460538   30.269882   32.636795       30.629999
17 2024-06-20  31.004751   29.694673   32.385267       30.620001
18 2024-06-21  30.509278   29.106407   31.819148       31.090000
21 2024-06-24  31.052002   29.542330   32.548505       30.570000
22 2024-06-25  31.487472   29.969323   33.024053       30.740000
23 2024-06-26  30.902940   29.447351   32.496848       30.540001
24 2024-06-27  31.031685   29.436412   32.630240       30.590000
25 2024-06-28  30.536212   28.931546   32.306923       30.969999

Model Evaluation Metrics for INTC:
MAE: 0.45
RMSE: 0.55
MAPE: 1.46%